// <auto-generated />
using System;
using System.Collections.Generic;
using FIFA_API.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FIFA_API.Migrations
{
    [DbContext(typeof(FifaDbContext))]
    [Migration("20240313145741_CreationBDDMigration")]
    partial class CreationBDDMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)")
                        .HasColumnName("adr_codepostal");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adr_rue");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adr_ville");

                    b.HasKey("Id");

                    b.ToTable("t_e_adresse_adr");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.CategorieProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cpr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCategorieProduitParent")
                        .HasColumnType("integer")
                        .HasColumnName("cpr_idparent");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cpr_nom");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorieProduitParent");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("t_e_categorieproduit_cpr");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clb_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clb_nom");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("t_e_club_clb");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCommande")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cmd_datecommande");

                    b.Property<DateTime>("DateExpedition")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cmd_dateexpedition");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cmd_datelivraison");

                    b.Property<int>("IdAdresseFacturation")
                        .HasColumnType("integer")
                        .HasColumnName("adr_facuration_id");

                    b.Property<int>("IdAdresseLivraison")
                        .HasColumnType("integer")
                        .HasColumnName("adr_livraison_id");

                    b.Property<int>("IdTypeLivraison")
                        .HasColumnType("integer")
                        .HasColumnName("tli_id");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("utl_id");

                    b.Property<decimal>("PrixLivraison")
                        .HasColumnType("numeric")
                        .HasColumnName("cmd_prixlivraison");

                    b.Property<string>("UrlFacture")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cmd_urlfacture");

                    b.HasKey("Id");

                    b.HasIndex("IdAdresseFacturation");

                    b.HasIndex("IdAdresseLivraison");

                    b.HasIndex("IdTypeLivraison");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("UrlFacture")
                        .IsUnique();

                    b.ToTable("t_e_commande_cmd");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cmp_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_competition_cmp");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Couleur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("col_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHexa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("col_codehexa");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("col_nom");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("t_e_couleur_col");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.FaqJoueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("faq_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdJoueur")
                        .HasColumnType("integer")
                        .HasColumnName("jou_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("faq_question");

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("faq_reponse");

                    b.HasKey("Id");

                    b.HasIndex("IdJoueur");

                    b.ToTable("t_e_faqjoueur_faq");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gen_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gen_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_genre_gen");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jou_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biographie")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("jou_biographie");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("jou_datenaissance");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clb_id");

                    b.Property<int>("IdPays")
                        .HasColumnType("integer")
                        .HasColumnName("pys_id");

                    b.Property<int>("IdPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("pht_id");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jou_lieunaissance");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jou_nom");

                    b.Property<int>("Pied")
                        .HasColumnType("integer")
                        .HasColumnName("jou_pied");

                    b.Property<int>("Poids")
                        .HasColumnType("integer")
                        .HasColumnName("jou_poids");

                    b.Property<int>("PosteJoueur")
                        .HasColumnType("integer")
                        .HasColumnName("jou_poste");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jou_prenom");

                    b.Property<int>("Taille")
                        .HasColumnType("integer")
                        .HasColumnName("jou_taille");

                    b.HasKey("Id");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdPays");

                    b.HasIndex("IdPhoto");

                    b.ToTable("t_e_joueur_jou");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Langue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lan_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_langue_lan");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lco_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    b.Property<int>("IdTaille")
                        .HasColumnType("integer")
                        .HasColumnName("tpr_id");

                    b.Property<int>("IdVCProduit")
                        .HasColumnType("integer")
                        .HasColumnName("prd_id");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2)")
                        .HasColumnName("lco_prixunitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("lco_quantite");

                    b.HasKey("Id");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdTaille");

                    b.HasIndex("IdVCProduit");

                    b.ToTable("t_e_lignecommande_lco");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nat_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_nation_nat");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Pays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pys_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pys_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_pays_pys");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pht_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int?>("BlogId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pht_nom");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pht_url");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("BlogId");

                    b.ToTable("t_e_photo_pht");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prd_description");

                    b.Property<int>("IdCategorieProduit")
                        .HasColumnType("integer")
                        .HasColumnName("cpr_id");

                    b.Property<int>("IdCompetition")
                        .HasColumnType("integer")
                        .HasColumnName("cmp_id");

                    b.Property<int>("IdGenre")
                        .HasColumnType("integer")
                        .HasColumnName("gen_id");

                    b.Property<int>("IdNation")
                        .HasColumnType("integer")
                        .HasColumnName("nat_id");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prd_titre");

                    b.HasKey("Id");

                    b.HasIndex("IdCategorieProduit");

                    b.HasIndex("IdCompetition");

                    b.HasIndex("IdGenre");

                    b.HasIndex("IdNation");

                    b.HasIndex("ProduitId");

                    b.ToTable("t_e_produit_prd");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pub_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pub_datepublication");

                    b.Property<int?>("IdPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("pht_id");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("pub_resume");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pub_titre");

                    b.HasKey("Id");

                    b.HasIndex("IdPhoto");

                    b.ToTable("t_g_publication_pub");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Statistiques", b =>
                {
                    b.Property<int>("IdJoueur")
                        .HasColumnType("integer")
                        .HasColumnName("jou_id");

                    b.Property<int>("Buts")
                        .HasColumnType("integer")
                        .HasColumnName("stt_buts");

                    b.Property<int>("MatchsJoues")
                        .HasColumnType("integer")
                        .HasColumnName("stt_matchsjoues");

                    b.Property<int>("MinutesJouees")
                        .HasColumnType("integer")
                        .HasColumnName("stt_minutesjouees");

                    b.Property<int>("Titularisations")
                        .HasColumnType("integer")
                        .HasColumnName("stt_titularisations");

                    b.HasKey("IdJoueur");

                    b.ToTable("t_e_statistiques_stt");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.StatusCommande", b =>
                {
                    b.Property<int>("IdCommande")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sco_commentaire");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sco_date");

                    b.HasKey("IdCommande");

                    b.ToTable("t_j_statuscommande_sco");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.StockProduit", b =>
                {
                    b.Property<int>("IdVCProduit")
                        .HasColumnType("integer")
                        .HasColumnName("vcp_id")
                        .HasColumnOrder(0);

                    b.Property<int>("IdTaille")
                        .HasColumnType("integer")
                        .HasColumnName("tpr_id")
                        .HasColumnOrder(1);

                    b.Property<int>("Stocks")
                        .HasColumnType("integer")
                        .HasColumnName("spr_stocks");

                    b.HasKey("IdVCProduit", "IdTaille");

                    b.HasIndex("IdTaille");

                    b.ToTable("t_j_stockproduit_spr");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.TailleProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tpr_nom");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("ProduitId");

                    b.ToTable("t_e_tailleproduit_tpr");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Trophee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tph_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tph_nom");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("t_e_trophee_tph");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.TypeLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tli_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxBusinessDays")
                        .HasColumnType("integer")
                        .HasColumnName("tli_maxbusinessdays");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tli_nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("tli_prix");

                    b.HasKey("Id");

                    b.ToTable("t_e_typelivraison_tli");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("utl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("utl_datenaissance");

                    b.Property<DateTime>("DateVerificationEmail")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utl_dateverificationemail");

                    b.Property<DateTime>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utl_derniereconnexion");

                    b.Property<bool>("DoubleAuthentification")
                        .HasColumnType("boolean")
                        .HasColumnName("utl_doubleauthentification");

                    b.Property<int>("IdLangue")
                        .HasColumnType("integer")
                        .HasColumnName("lan_id");

                    b.Property<int>("IdPays")
                        .HasColumnType("integer")
                        .HasColumnName("pys_idpays");

                    b.Property<int>("IdPaysFavori")
                        .HasColumnType("integer")
                        .HasColumnName("utl_idpaysfavori");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utl_mail");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utl_motdepasse");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utl_prenom");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("utl_role");

                    b.Property<string>("StripeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utl_stripeid");

                    b.Property<string>("Surnom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utl_surnom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("utl_telephone");

                    b.HasKey("Id");

                    b.HasIndex("IdLangue");

                    b.HasIndex("IdPays");

                    b.HasIndex("IdPaysFavori");

                    b.ToTable("t_e_utilisateur_utl");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.VarianteCouleurProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vcp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCouleur")
                        .HasColumnType("integer")
                        .HasColumnName("col_id")
                        .HasColumnOrder(1);

                    b.Property<int>("IdProduit")
                        .HasColumnType("integer")
                        .HasColumnName("prd_id")
                        .HasColumnOrder(0);

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("varchar[]")
                        .HasColumnName("vcp_images");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("vcp_prix");

                    b.HasKey("Id");

                    b.HasIndex("IdCouleur");

                    b.HasIndex("IdProduit", "IdCouleur")
                        .IsUnique();

                    b.ToTable("t_j_variantecouleurproduit_vcp");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vid_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("vid_nom");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("vid_url");

                    b.HasKey("Id");

                    b.ToTable("t_e_video_vid");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.VoteUtilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("utl_id")
                        .HasColumnOrder(0);

                    b.Property<int>("IdCouleur")
                        .HasColumnType("integer")
                        .HasColumnName("col_id")
                        .HasColumnOrder(1);

                    b.Property<int>("IdTaille")
                        .HasColumnType("integer")
                        .HasColumnName("tpr_id")
                        .HasColumnOrder(2);

                    b.Property<int>("RankVote")
                        .HasColumnType("integer")
                        .HasColumnName("vtl_rankvote");

                    b.HasKey("IdUtilisateur", "IdCouleur", "IdTaille");

                    b.HasIndex("IdCouleur");

                    b.HasIndex("IdTaille");

                    b.ToTable("t_e_voteutilisateur_vtl");
                });

            modelBuilder.Entity("JoueurTrophee", b =>
                {
                    b.Property<int>("JoueursId")
                        .HasColumnType("integer");

                    b.Property<int>("TropheesId")
                        .HasColumnType("integer");

                    b.HasKey("JoueursId", "TropheesId");

                    b.HasIndex("TropheesId");

                    b.ToTable("JoueurTrophee");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Album", b =>
                {
                    b.HasBaseType("FIFA_API.Models.EntityFramework.Publication");

                    b.ToTable("t_h_album_alb");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Article", b =>
                {
                    b.HasBaseType("FIFA_API.Models.EntityFramework.Publication");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("art_texte");

                    b.ToTable("t_h_article_art");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Blog", b =>
                {
                    b.HasBaseType("FIFA_API.Models.EntityFramework.Publication");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blg_texte");

                    b.ToTable("t_h_blog_blg");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Document", b =>
                {
                    b.HasBaseType("FIFA_API.Models.EntityFramework.Publication");

                    b.Property<string>("UrlPdf")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("doc_urlpdf");

                    b.ToTable("t_h_document_doc");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.CategorieProduit", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.CategorieProduit", "Parent")
                        .WithMany("SousCategories")
                        .HasForeignKey("IdCategorieProduitParent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Adresse", "AdresseFacturation")
                        .WithMany()
                        .HasForeignKey("IdAdresseFacturation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Adresse", "AdresseLivraison")
                        .WithMany()
                        .HasForeignKey("IdAdresseLivraison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.TypeLivraison", "TypeLivraison")
                        .WithMany("Commandes")
                        .HasForeignKey("IdTypeLivraison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseFacturation");

                    b.Navigation("AdresseLivraison");

                    b.Navigation("TypeLivraison");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Couleur", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Produit", null)
                        .WithMany("Couleurs")
                        .HasForeignKey("ProduitId");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.FaqJoueur", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Joueur", "Joueur")
                        .WithMany("FaqJoueurs")
                        .HasForeignKey("IdJoueur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Joueur", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("IdPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("IdPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Pays");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.LigneCommande", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.TailleProduit", "Taille")
                        .WithMany()
                        .HasForeignKey("IdTaille")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.VarianteCouleurProduit", "VCProduit")
                        .WithMany()
                        .HasForeignKey("IdVCProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Taille");

                    b.Navigation("VCProduit");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Photo", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Album", null)
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId");

                    b.HasOne("FIFA_API.Models.EntityFramework.Blog", null)
                        .WithMany("Photos")
                        .HasForeignKey("BlogId");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Produit", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.CategorieProduit", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("IdCategorieProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Competition", "Competition")
                        .WithMany("Produits")
                        .HasForeignKey("IdCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Nation", "Nation")
                        .WithMany("Produits")
                        .HasForeignKey("IdNation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Produit", null)
                        .WithMany("Associes")
                        .HasForeignKey("ProduitId");

                    b.Navigation("Categorie");

                    b.Navigation("Competition");

                    b.Navigation("Genre");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Publication", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("IdPhoto");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Statistiques", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Joueur", "Joueur")
                        .WithOne("Stats")
                        .HasForeignKey("FIFA_API.Models.EntityFramework.Statistiques", "IdJoueur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.StatusCommande", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Commande", "Commande")
                        .WithMany("Status")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.StockProduit", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.TailleProduit", "Taille")
                        .WithMany()
                        .HasForeignKey("IdTaille")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.VarianteCouleurProduit", "VCProduit")
                        .WithMany()
                        .HasForeignKey("IdVCProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taille");

                    b.Navigation("VCProduit");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.TailleProduit", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Produit", null)
                        .WithMany("Tailles")
                        .HasForeignKey("ProduitId");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Utilisateur", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Langue", "Langue")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdLangue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Pays", "Pays")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Pays", "PaysFavori")
                        .WithMany()
                        .HasForeignKey("IdPaysFavori")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Langue");

                    b.Navigation("Pays");

                    b.Navigation("PaysFavori");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.VarianteCouleurProduit", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Couleur", "Couleur")
                        .WithMany()
                        .HasForeignKey("IdCouleur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Couleur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.VoteUtilisateur", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Couleur", "Couleur")
                        .WithMany()
                        .HasForeignKey("IdCouleur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.TailleProduit", "Taille")
                        .WithMany()
                        .HasForeignKey("IdTaille")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Couleur");

                    b.Navigation("Taille");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("JoueurTrophee", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Joueur", null)
                        .WithMany()
                        .HasForeignKey("JoueursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIFA_API.Models.EntityFramework.Trophee", null)
                        .WithMany()
                        .HasForeignKey("TropheesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Album", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Publication", null)
                        .WithOne()
                        .HasForeignKey("FIFA_API.Models.EntityFramework.Album", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Article", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Publication", null)
                        .WithOne()
                        .HasForeignKey("FIFA_API.Models.EntityFramework.Article", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Blog", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Publication", null)
                        .WithOne()
                        .HasForeignKey("FIFA_API.Models.EntityFramework.Blog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Document", b =>
                {
                    b.HasOne("FIFA_API.Models.EntityFramework.Publication", null)
                        .WithOne()
                        .HasForeignKey("FIFA_API.Models.EntityFramework.Document", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.CategorieProduit", b =>
                {
                    b.Navigation("Produits");

                    b.Navigation("SousCategories");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Commande", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Competition", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Joueur", b =>
                {
                    b.Navigation("FaqJoueurs");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Langue", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Nation", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Pays", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Produit", b =>
                {
                    b.Navigation("Associes");

                    b.Navigation("Couleurs");

                    b.Navigation("Tailles");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.TypeLivraison", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Album", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("FIFA_API.Models.EntityFramework.Blog", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
